added uptime module
davidscholberg/goblocks pull request #8
Opened 2016-11-22 23:48 UTC by MagiCrazy

Hi,
I added an uptime module I would like to share.
Tell me if everything's right.

2016-11-23 14:11 UTC, davidscholberg requested changes
Thank you for this pull request! It looks great. There's just a small typo in the example config, but otherwise the code is fine.

2016-11-23 14:11 UTC, davidscholberg commented on config/goblocks-full.yml
> +    - type: Uptime
This should be lowercase.

2016-11-23 20:08 UTC, MagiCrazy commented
That's OK for me =)

2016-12-06 10:52 UTC, MagiCrazy commented
up! is there a problem with my fix?

2016-12-06 17:28 UTC, davidscholberg commented
Sorry, I've been busy lately. I'll try to get to this sometime this week.

2016-12-11 16:03 UTC, davidscholberg approved these changes

2016-12-11 16:05 UTC, merged

2016-12-11 16:08 UTC, davidscholberg commented
Thank you, @MagiCrazy.

I think it would be nice if there was a config option to specify a time format to use for the uptime module, just like the time module does. If you have any interest in adding that feature, please let me know. Otherwise, I'll probably add it myself.

2016-12-11 16:27 UTC, MagiCrazy commented
Great idea, I'll add it when I have some time too, if you didn't already.

On Sun, Dec 11, 2016, 17:08 David Scholberg <notifications@github.com>
wrote:

> Thank you, @MagiCrazy <https://github.com/MagiCrazy>.
>
> I think it would be nice if there was a config option to specify a time
> format to use for the uptime module, just like the time module does. If you
> have any interest in adding that feature, please let me know. Otherwise,
> I'll probably add it myself.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/davidscholberg/goblocks/pull/8#issuecomment-266290406>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFSq32aCmINpC7dmIRI_xlo7S9bAFYWNks5rHCASgaJpZM4K6FGG>
> .
>

2016-12-11 17:28 UTC, davidscholberg commented
Go for it :)

2016-12-26 22:12 UTC, davidscholberg commented
@MagiCrazy I looked into this a little, and it turns out that Go doesn't seem to have built-in handling for formatting durations, which makes this feature somewhat non-trivial to implement. If you haven't already started, don't worry about doing this feature. I'll take care of it.

2016-12-27 14:28 UTC, MagiCrazy commented
@davidscholberg I looked into it too, and went to the same conclusion.

2017-01-22 17:00 UTC, davidscholberg commented
@MagiCrazy FYI, I added custom formatting for durations in commit a02fcfce91cfb0e7b5830dcd76b6ea9ba65f1378.